name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn workspace ember-cli-mirage lint

      - name: Run Tests
        run: yarn workspace ember-cli-mirage test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --no-lockfile

      - name: Run Tests
        run: yarn test:ember
        working-directory: packages/ember-cli-mirage

  test-docs:
    name: "Docs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --no-lockfile

      - name: Lint
        run: yarn workspace ember-cli-mirage-docs lint

      - name: Run Tests
        run: yarn workspace ember-cli-mirage-docs test:ember

  test-app-01:
    name: "Tests - Basic App"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn workspace basic-app lint

      - name: Run Tests
        run: yarn workspace basic-app test

  test-app-02:
    name: "Tests - App That Excludes Mirage"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn workspace app-that-excludes-mirage lint

      - name: Run Tests
        run: yarn workspace app-that-excludes-mirage test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
#          - embroider-safe
#          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: packages/ember-cli-mirage
