name: deploy docs

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
        working-directory: packages/ember-cli-mirage

      - name: Run Browser Tests
        run: pnpm run test:ember
        working-directory: packages/ember-cli-mirage

      - name: deploy docs
        run: node_modules/.bin/ember deploy production
        working-directory: packages/ember-cli-mirage
