name: deploy docs

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
        working-directory: packages/ember-cli-mirage

      - name: Run Browser Tests
        run: pnpm run test:ember
        working-directory: packages/ember-cli-mirage

      - name: deploy docs
        run: pnpm run deploy
        working-directory: packages/ember-cli-mirage-docs
