name: CI Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: pnpm install

      - name: Copy .md files
        run: cp CHANGELOG.md LICENSE.md README.md packages/ember-cli-mirage/

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: packages/ember-cli-mirage
