name: CI Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
          # This creates an .npmrc that reads the NODE_AUTH_TOKEN environment variable
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy .md files
        run: cp CHANGELOG.md LICENSE.md README.md packages/ember-cli-mirage/

      - name: pnpm publish
        run: pnpm publish --tag=latest --no-git-checks --filter ember-cli-mirage
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
